wander_area: 
    - [-5.0,-18.0]
    - [5.0,-18.0]
    - [5.0,-17.0]
    - [-2.0,-17.0]
    - [-2.0,0.0]
    - [0.0,0.0]
    - [0.0,3.5]
    - [5.0,3.5]
    - [5.0,5.0]
    - [-5.0,5.0]
follow_area: 
    - [-5.0,-18.0]
    - [5.0,-18.0]
    - [5.0,-17.0]
    - [-2.0,-17.0]
    - [-2.0,0.0]
    - [0.0,0.0]
    - [0.0,3.5]
    - [5.0,3.5]
    - [5.0,5.0]
    - [-5.0,5.0]
wait_point: [-3.5,4.0,0.0,0.0,0.0,-1.14,1.0] # [x,y,z,alpha,peta,ceta,w]
alpha: 0.1
max_t_frames: 150
distance: 1.5
